// src/lib/components/results/FlashlightCard.svelte
<script lang="ts">
	import type { ColumnDef, FlashlightDB } from '$lib/schema/columns.js';
	import { urlState } from '$lib/state/url-state.svelte.js';
	import { starredState } from '$lib/state/starred.svelte.js';
	import SpriteImage from './SpriteImage.svelte';
	import { smartFixed } from '$lib/schema/si-prefix.js';

	interface Props {
		index: number;
		db: FlashlightDB;
		columns: ColumnDef[];
	}

	let { index, db, columns }: Props = $props();

	let data = $derived(db.data[index]);
	let expanded = $state(false);

	// Column indices
	let modelCol = $derived(db.head.indexOf('model'));
	let brandCol = $derived(db.head.indexOf('brand'));
	let picCol = $derived(db.head.indexOf('_pic'));
	let infoCol = $derived(db.head.indexOf('info'));
	let priceCol = $derived(db.head.indexOf('price'));
	let purchaseCol = $derived(db.head.indexOf('purchase'));
	let reviewsCol = $derived(db.head.indexOf('_reviews'));

	let model = $derived(modelCol >= 0 ? String(data[modelCol] ?? '') : '');
	let brand = $derived(brandCol >= 0 ? String(data[brandCol] ?? '') : '');
	// _pic can be [col, row] sprite coords OR a direct image URL string
	let picRaw = $derived(picCol >= 0 ? data[picCol] : null);
	let picIsSprite = $derived(Array.isArray(picRaw));
	let picCoords = $derived(picIsSprite ? picRaw as [number, number] : [0, 0] as [number, number]);
	let picUrl = $derived(!picIsSprite && typeof picRaw === 'string' && picRaw ? picRaw : '');
	let isStarred = $derived(starredState.isStarred(index));

	// Avoid list for detail display (same as parametrek.js)
	const avoidIds = new Set(['model', 'brand', 'info', 'purchase', 'price']);

	/** Should this column's detail row be visible? */
	function shouldShowDetail(col: ColumnDef): boolean {
		if (col.cvis === 'never') return false;
		if (avoidIds.has(col.id)) return false;
		if (col.cvis === 'always') return true;
		if (expanded) return true;
		// Show if filter is active for this column
		if (urlState.filters.has(col.index)) return true;
		// Show if linked column has active filter
		const linkCol = columns.find((c) => c.id === col.link);
		if (linkCol && urlState.filters.has(linkCol.index)) return true;
		return false;
	}

	/** Format a data value for display */
	function formatValue(col: ColumnDef, value: unknown): string {
		if (value === '' || value === null || value === undefined) return '?';

		if (Array.isArray(value)) {
			if (col.filterType === 'boolean') {
				const filtered = value.filter(
					(x) => typeof x !== 'string' || (!x.startsWith('~') && !x.startsWith('//'))
				);
				return filtered.length > 0 ? filtered.join('  ') : 'none';
			}
			const filtered = value.filter((x) => typeof x !== 'string' || !x.startsWith('//'));
			return filtered.join('  ');
		}

		return String(value);
	}

	/** Format with unit template */
	function formatWithUnit(col: ColumnDef, value: unknown): string {
		const display = formatValue(col, value);
		if (display === '?') return '?';

		if (col.unit === '{link}') {
			if (Array.isArray(value)) {
				return (value as string[])
					.filter((u) => u)
					.map((u) => {
						const domain = extractDomain(u);
						return `<a href="${u}" target="_blank" rel="noopener" class="underline" style="color: var(--accent);">${domain}</a>`;
					})
					.join(', ');
			}
			const url = String(value);
			const domain = extractDomain(url);
			return `<a href="${url}" target="_blank" rel="noopener" class="underline" style="color: var(--accent);">${domain}</a>`;
		}

		return col.unit.replace('{}', display);
	}

	function extractDomain(url: string): string {
		const match = url.match(/\/([a-zA-Z0-9_.-]+)\//);
		if (!match) return '';
		return match[1].replace(/^www\./, '');
	}

	function getPrice(): string {
		if (priceCol < 0) return '';
		const amount = data[priceCol];
		if (!amount && amount !== 0) return '';
		const num = Number(amount);
		const formatted = num % 1 !== 0 ? num.toFixed(2) : String(num);
		return columns[priceCol].unit.replace('{}', formatted);
	}

	function getPurchaseLinks(): string {
		if (purchaseCol < 0 || !data[purchaseCol]) return '';
		const urls = Array.isArray(data[purchaseCol]) ? data[purchaseCol] as string[] : [String(data[purchaseCol])];
		return urls
			.filter((u) => u)
			.map((u) => {
				const domain = extractDomain(u);
				return `<a href="${u}" target="_blank" rel="noopener" class="underline" style="color: var(--accent);">${domain}</a>`;
			})
			.join(', ');
	}

	function getInfoLinks(): string {
		if (infoCol < 0 || !data[infoCol]) return '';
		const urls = Array.isArray(data[infoCol]) ? data[infoCol] as string[] : [String(data[infoCol])];
		return urls
			.filter((u) => u)
			.map((u) => {
				const domain = extractDomain(u);
				return `<a href="${u}" target="_blank" rel="noopener" class="underline text-xs" style="color: var(--accent);">${domain}</a>`;
			})
			.join(', ');
	}
</script>

<div class="result-item-wrap">
<div
	class="card-row"
>
	<!-- Sprite thumbnail -->
	<div class="card-thumb">
		<SpriteImage col={picCoords[0]} row={picCoords[1]} spriteUrl={db.sprite} imageUrl={picUrl} />
	</div>

	<!-- Content -->
	<div class="card-body">
		<!-- Header row: expand toggle, model name, brand, star, price -->
		<div class="card-header">
			<button
				class="card-expand"
				onclick={() => (expanded = !expanded)}
				title="Toggle details"
			>±</button>
			<span class="card-model">{model}</span>
			<span class="card-brand">by {brand}</span>
			{#if getInfoLinks()}
				<span class="card-info">({@html getInfoLinks()})</span>
			{/if}
			<span class="card-spacer"></span>
			<button
				class="card-star"
				class:starred={isStarred}
				onclick={() => starredState.toggle(index)}
				title={isStarred ? 'Remove from favorites' : 'Add to favorites'}
			>
				{isStarred ? '★' : '☆'}
			</button>
			{#if getPrice()}
				<span class="card-price">{getPrice()}</span>
			{/if}
		</div>

		<!-- Detail rows -->
		<div class="card-details">
			{#each columns as col}
				{#if shouldShowDetail(col)}
					<span class="card-detail">
						<span class="detail-label">{@html col.display}:</span>
						{@html formatWithUnit(col, data[col.index])}
					</span>
				{/if}
			{/each}
		</div>

		<!-- Purchase links -->
		{#if getPurchaseLinks() || (reviewsCol >= 0 && data[reviewsCol] && Number(data[reviewsCol]) > 0)}
			<div class="card-purchase">
				{#if getPurchaseLinks()}
					<span>{@html getPurchaseLinks()}</span>
				{/if}
				{#if reviewsCol >= 0 && data[reviewsCol] && Number(data[reviewsCol]) > 0}
					<span class="card-reviews">({data[reviewsCol]} review{Number(data[reviewsCol]) > 1 ? 's' : ''})</span>
				{/if}
			</div>
		{/if}
	</div>
</div>
</div>

<style>
	.card-row {
		display: flex;
		gap: 0.75rem;
		padding: 0.5rem 0.75rem;
		border-radius: 0.5rem;
		border: 1px solid var(--border);
		background: var(--bg-secondary);
		transition: border-color 0.15s;
	}
	.card-row:hover {
		border-color: var(--border-hover);
	}

	.card-thumb {
		flex-shrink: 0;
	}

	.card-body {
		flex: 1;
		min-width: 0;
	}

	.card-header {
		display: flex;
		align-items: baseline;
		gap: 0.375rem;
		flex-wrap: wrap;
	}

	.card-expand {
		font-size: 0.8rem;
		cursor: pointer;
		color: var(--text-muted);
		background: none;
		border: none;
		padding: 0;
		user-select: none;
	}

	.card-model {
		font-weight: 600;
		font-size: 0.875rem;
		color: var(--text-primary);
		white-space: nowrap;
	}

	.card-brand {
		font-size: 0.75rem;
		color: var(--text-secondary);
		white-space: nowrap;
	}

	.card-info {
		font-size: 0.7rem;
		color: var(--text-muted);
	}

	.card-spacer {
		flex: 1;
	}

	.card-star {
		font-size: 1rem;
		cursor: pointer;
		color: var(--text-muted);
		background: none;
		border: none;
		padding: 0;
		user-select: none;
		flex-shrink: 0;
	}
	.card-star.starred {
		color: var(--star);
	}

	.card-price {
		font-weight: 600;
		font-size: 0.875rem;
		color: var(--text-primary);
		white-space: nowrap;
		flex-shrink: 0;
	}

	.card-details {
		margin-top: 0.125rem;
		display: flex;
		flex-wrap: wrap;
		gap: 0.125rem 0.75rem;
		font-size: 0.75rem;
		color: var(--text-secondary);
		line-height: 1.4;
	}

	.detail-label {
		color: var(--text-muted);
		font-weight: 500;
		margin-right: 0.2rem;
	}

	.card-purchase {
		margin-top: 0.25rem;
		font-size: 0.7rem;
		display: flex;
		gap: 0.5rem;
		align-items: baseline;
		flex-wrap: wrap;
	}

	.card-reviews {
		color: var(--text-muted);
	}

	/* Mobile: smaller thumb, tighter spacing */
	@media (max-width: 640px) {
		.card-row {
			padding: 0.375rem 0.5rem;
			gap: 0.5rem;
		}
	}
</style>

// src/components/results/FlashlightCard.tsx
import { useState, useMemo, useCallback, memo } from 'react';
import type { ColumnDef, FlashlightDB } from '$lib/schema/columns';
import { useUrlState } from '$lib/state/url-state';
import { useStarred } from '$lib/state/starred';
import SpriteImage from './SpriteImage';
import { smartFixed } from '$lib/schema/si-prefix';

interface Props {
	index: number;
	db: FlashlightDB;
	columns: ColumnDef[];
}

/** Columns excluded from detail display (shown in header or special sections) */
const avoidIds = new Set(['model', 'brand', 'info', 'purchase', 'price']);

/** Validate URL uses a safe protocol */
function isSafeUrl(url: string): boolean {
	try {
		const parsed = new URL(url);
		return parsed.protocol === 'http:' || parsed.protocol === 'https:';
	} catch {
		return false;
	}
}

function extractDomain(url: string): string {
	try {
		const parsed = new URL(url);
		return parsed.hostname.replace(/^www\./, '');
	} catch {
		return '';
	}
}

export default memo(function FlashlightCard({ index, db, columns }: Props) {
	const filters = useUrlState((s) => s.filters);
	const toggle = useStarred((s) => s.toggle);
	const isStarred = useStarred((s) => s.starred.has(index));
	const [expanded, setExpanded] = useState(false);

	const data = db.data[index];

	// Column indices — computed once from the db header
	const colIndices = useMemo(() => ({
		model: db.head.indexOf('model'),
		brand: db.head.indexOf('brand'),
		pic: db.head.indexOf('_pic'),
		info: db.head.indexOf('info'),
		price: db.head.indexOf('price'),
		purchase: db.head.indexOf('purchase'),
		reviews: db.head.indexOf('_reviews'),
	}), [db.head]);

	const model = colIndices.model >= 0 ? String(data[colIndices.model] ?? '') : '';
	const brand = colIndices.brand >= 0 ? String(data[colIndices.brand] ?? '') : '';

	// _pic can be [col, row] sprite coords OR a direct image URL string
	const picRaw = colIndices.pic >= 0 ? data[colIndices.pic] : null;
	const picIsSprite = picRaw != null && typeof picRaw === 'object' && Array.isArray(picRaw) && picRaw.length === 2;
	const picCoords: [number, number] = picIsSprite ? [Number((picRaw as number[])[0]), Number((picRaw as number[])[1])] : [0, 0];
	const picUrl = !picIsSprite && typeof picRaw === 'string' && picRaw ? picRaw : '';

	/** Should this column's detail row be visible? */
	const shouldShowDetail = useCallback((col: ColumnDef): boolean => {
		if (col.cvis === 'never') return false;
		if (avoidIds.has(col.id)) return false;
		if (col.cvis === 'always') return true;
		if (expanded) return true;
		if (filters.has(col.index)) return true;
		const linkCol = columns.find((c) => c.id === col.link);
		if (linkCol && filters.has(linkCol.index)) return true;
		return false;
	}, [expanded, filters, columns]);

	/** Format a data value for display */
	const formatValue = useCallback((col: ColumnDef, value: unknown): string => {
		if (value === '' || value === null || value === undefined) return '?';
		if (Array.isArray(value)) {
			if (col.filterType === 'boolean') {
				const filtered = value.filter((x) => typeof x !== 'string' || (!x.startsWith('~') && !x.startsWith('//')));
				return filtered.length > 0 ? filtered.join('  ') : 'none';
			}
			const filtered = value.filter((x) => typeof x !== 'string' || !x.startsWith('//'));
			return filtered.join('  ');
		}
		return String(value);
	}, []);

	/** Format with unit template (may produce HTML for links) */
	const formatWithUnit = useCallback((col: ColumnDef, value: unknown): string => {
		const display = formatValue(col, value);
		if (display === '?') return '?';

		if (col.unit === '{link}') {
			if (Array.isArray(value)) {
				return (value as string[])
					.filter((u) => u && isSafeUrl(u))
					.map((u) => {
						const domain = extractDomain(u);
						return `<a href="${u}" target="_blank" rel="noopener" class="underline" style="color: var(--accent);">${domain}</a>`;
					})
					.join(', ');
			}
			const url = String(value);
			if (!isSafeUrl(url)) return extractDomain(url) || '?';
			const domain = extractDomain(url);
			return `<a href="${url}" target="_blank" rel="noopener" class="underline" style="color: var(--accent);">${domain}</a>`;
		}

		return col.unit.replace('{}', display);
	}, [formatValue]);

	const price = useMemo(() => {
		if (colIndices.price < 0) return '';
		const amount = data[colIndices.price];
		if (!amount && amount !== 0) return '';
		const num = Number(amount);
		const formatted = num % 1 !== 0 ? num.toFixed(2) : String(num);
		return columns[colIndices.price].unit.replace('{}', formatted);
	}, [data, colIndices.price, columns]);

	const purchaseLinks = useMemo(() => {
		if (colIndices.purchase < 0 || !data[colIndices.purchase]) return '';
		const urls = Array.isArray(data[colIndices.purchase]) ? data[colIndices.purchase] as string[] : [String(data[colIndices.purchase])];
		return urls
			.filter((u) => u && isSafeUrl(u))
			.map((u) => `<a href="${u}" target="_blank" rel="noopener" class="underline" style="color: var(--accent);">${extractDomain(u)}</a>`)
			.join(', ');
	}, [data, colIndices.purchase]);

	const infoLinks = useMemo(() => {
		if (colIndices.info < 0 || !data[colIndices.info]) return '';
		const urls = Array.isArray(data[colIndices.info]) ? data[colIndices.info] as string[] : [String(data[colIndices.info])];
		return urls
			.filter((u) => u && isSafeUrl(u))
			.map((u) => `<a href="${u}" target="_blank" rel="noopener" class="underline text-xs" style="color: var(--accent);">${extractDomain(u)}</a>`)
			.join(', ');
	}, [data, colIndices.info]);

	const reviewCount = colIndices.reviews >= 0 && data[colIndices.reviews] ? Number(data[colIndices.reviews]) : 0;

	return (
		<div className="result-item-wrap">
			<div className="card-row">
				{/* Sprite thumbnail */}
				<div className="card-thumb">
					<SpriteImage col={picCoords[0]} row={picCoords[1]} spriteUrl={db.sprite} imageUrl={picUrl} />
				</div>

				{/* Content */}
				<div className="card-body">
					{/* Header row */}
					<div className="card-header">
						<button className="card-expand" onClick={() => setExpanded(!expanded)} title="Toggle details">±</button>
						<span className="card-model">{model}</span>
						<span className="card-brand">by {brand}</span>
						{infoLinks && (
							<span className="card-info" dangerouslySetInnerHTML={{ __html: `(${infoLinks})` }} />
						)}
						<span className="card-spacer" />
						<button
							className={`card-star ${isStarred ? 'starred' : ''}`}
							onClick={() => toggle(index)}
							title={isStarred ? 'Remove from favorites' : 'Add to favorites'}
						>
							{isStarred ? '★' : '☆'}
						</button>
						{price && <span className="card-price">{price}</span>}
					</div>

					{/* Detail rows */}
					<div className="card-details">
						{columns.map((col) =>
							shouldShowDetail(col) ? (
								<span key={col.index} className="card-detail">
									<span className="detail-label" dangerouslySetInnerHTML={{ __html: col.display + ':' }} />
									<span dangerouslySetInnerHTML={{ __html: formatWithUnit(col, data[col.index]) }} />
								</span>
							) : null
						)}
					</div>

					{/* Purchase links */}
					{(purchaseLinks || reviewCount > 0) && (
						<div className="card-purchase">
							{purchaseLinks && <span dangerouslySetInnerHTML={{ __html: purchaseLinks }} />}
							{reviewCount > 0 && (
								<span className="card-reviews">({reviewCount} review{reviewCount > 1 ? 's' : ''})</span>
							)}
						</div>
					)}
				</div>
			</div>
		</div>
	);
});
