// src/components/filters/FilterGroup.tsx
import { memo } from 'react';
import type { ColumnDef } from '$lib/schema/columns';
import MultiFilter from './MultiFilter';
import BooleanFilter from './BooleanFilter';
import RangeFilter from './RangeFilter';
import CompositeFilter from './CompositeFilter';

interface Props {
	column: ColumnDef;
	allColumns: ColumnDef[];
}

export default memo(function FilterGroup({ column, allColumns }: Props) {
	switch (column.filterType) {
		case 'multi':
		case 'mega-multi':
			return <MultiFilter column={column} />;
		case 'boolean':
			return <BooleanFilter column={column} />;
		case 'range':
			return <RangeFilter column={column} />;
		case 'log-range':
			return <RangeFilter column={column} isLog />;
		case 'multiple':
			return <CompositeFilter column={column} allColumns={allColumns} />;
		default:
			return null;
	}
});

// torch/src/lib/components/filters/FilterGroup.svelte
<script lang="ts">
	import type { ColumnDef } from '$lib/schema/columns.js';
	import MultiFilter from './MultiFilter.svelte';
	import BooleanFilter from './BooleanFilter.svelte';
	import RangeFilter from './RangeFilter.svelte';
	import CompositeFilter from './CompositeFilter.svelte';

	interface Props {
		column: ColumnDef;
		allColumns: ColumnDef[];
	}

	let { column, allColumns }: Props = $props();
</script>

{#if column.filterType === 'multi' || column.filterType === 'mega-multi'}
	<MultiFilter {column} />
{:else if column.filterType === 'boolean'}
	<BooleanFilter {column} />
{:else if column.filterType === 'range'}
	<RangeFilter {column} />
{:else if column.filterType === 'log-range'}
	<RangeFilter {column} isLog={true} />
{:else if column.filterType === 'multiple'}
	<CompositeFilter {column} {allColumns} />
{/if}
