// src/lib/components/filters/CompositeFilter.svelte
<script lang="ts">
	import type { ColumnDef } from '$lib/schema/columns.js';
	import FilterGroup from './FilterGroup.svelte';

	interface Props {
		column: ColumnDef;
		allColumns: ColumnDef[];
	}

	let { column, allColumns }: Props = $props();

	let subColumns = $derived(
		(column.subColumns ?? []).map((idx) => allColumns[idx]).filter(Boolean)
	);
</script>

<div class="space-y-3">
	{#each subColumns as subCol}
		<div>
			<div class="text-xs font-medium mb-1" style="color: var(--text-secondary);">
				{@html subCol.display}
			</div>
			<FilterGroup column={subCol} allColumns={allColumns} />
		</div>
	{/each}
</div>

// src/components/filters/CompositeFilter.tsx
import { memo, useMemo } from 'react';
import type { ColumnDef } from '$lib/schema/columns';
import FilterGroup from './FilterGroup';

interface Props {
	column: ColumnDef;
	allColumns: ColumnDef[];
}

export default memo(function CompositeFilter({ column, allColumns }: Props) {
	const subColumns = useMemo(
		() => (column.subColumns ?? []).map((idx) => allColumns[idx]).filter(Boolean),
		[column.subColumns, allColumns]
	);

	return (
		<div className="space-y-3">
			{subColumns.map((subCol) => (
				<div key={subCol.index}>
					<div
						className="text-xs font-medium mb-1"
						style={{ color: 'var(--text-secondary)' }}
						dangerouslySetInnerHTML={{ __html: subCol.display }}
					/>
					<FilterGroup column={subCol} allColumns={allColumns} />
				</div>
			))}
		</div>
	);
});
